# Generated by Django 5.2.11 on 2026-02-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderstatus'),
        ('customer', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderstatus',
        ),
    ]
