# Generated by Django 5.2.11 on 2026-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_productimage_image_url_productimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(max_length=255),
        ),
    ]
