# Generated by Django 5.2.11 on 2026-03-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_order_order_status'),
        ('seller', '0006_return_delete_inventorylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
