# Generated by Django 5.2.11 on 2026-02-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('core', '0001_initial'),
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.discount'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.offer'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.discount'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.offer'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.orderitem'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.discount'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.offer'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
